import json

translation_dict = {
# FEATURES
"Gaz tasarruf ünitesi ve debimetre": "Gas saving unit and flowmeter",
"Ayarlanabilir kesim açısı": "Adjustable cutting angle",
"Römork üstü mobil tasarım": "Trailer-mounted mobile design",
"Ayarlanabilir serim genişliği": "Adjustable paving width",
"Uzaktan kumandalı operasyon": "Remote-controlled operation",
"Tek kademeli üstün performans": "Single-stage superior performance",
"Hidrostatik sürüş sistemi": "Hydrostatic drive system",
"Ağır çalışma koşullarına dayanıklı gövde": "Heavy-duty body",
"3 vitesli şanzıman": "3-speed gearbox",
"Otomatik ilerleme": "Automatic feed",
"Geniş gaz uyumluluğu": "Wide gas compatibility",
"Korumalı arka kapak": "Protected rear cover",
"Kolay taşınabilir tasarım": "Easily portable design",
"Yüksek devirli motor": "High-speed motor",
"Hassas regülatörler": "Precision regulators",
"Maksimum 300mm kesme derinliği": "Max 300mm cutting depth",
"Aşağı yönlü çıkış tasarımı": "Downward outlet design",
"Galvanizli su teknesi": "Galvanized water tank",
"Kolay okunabilir manometreler": "Easy-to-read pressure gauges",
"Ergonomik kullanım paneli": "Ergonomic control panel",
"Dahili alev geri tepme ventili": "Built-in flashback arrestor",
"Geniş disk çapı uyumu": "Wide blade diameter compatibility",
"Alüminyum gövde": "Aluminum body",
"Dahili su deposu": "Built-in water tank",
"Toz korumalı ayna": "Dust-protected chuck",
"Hızlı kurulum": "Quick setup",
"Sürekli çalışma kilidi": "Continuous operation lock",
"Ergonomik kullanım volanı": "Ergonomic control wheel",
"Kompakt ebatlar": "Compact dimensions",
"Daha az tüp değişimi ve daha yüksek verimlilik": "Fewer cylinder changes and higher efficiency",
"MIG/MAG/TIG için tüm koruyucu gazlarla uyumlu": "Compatible with all shielding gases for MIG/MAG/TIG",
"Titreşim emici sap (RVA)": "Vibration-absorbing handle (RVA)",
"Geniş kasnak depolama": "Large pulley storage",
"Porozitesiz, mükemmel kaynak kalitesi": "Porosity-free, excellent welding quality",
"Aşırı yük koruma sistemi": "Overload protection system",
"Kaynak çevresinde istikrarlı gaz akışı": "Stable gas flow around the weld",
"Ergonomik hamlaç": "Ergonomic torch",
"Pnömatik germe sistemi": "Pneumatic tensioning system",
"Pirinç gövde tasarımı": "Brass body design",
"Isıtmalı tabla sistemi": "Heated screed system",
"Modüler ray sistemi": "Modular rail system",
"Yüksek kesim kapasitesi": "High cutting capacity",
"Yüksek basınç hassasiyeti": "High pressure precision",
"Joystick kontrolü": "Joystick control",
"Honda benzinli motor": "Honda petrol engine",
"Elektronik hız ayarı": "Electronic speed control",
"Hidrolik tahrik mekanizması": "Hydraulic drive mechanism",
"Yüksek kesim hızı": "High cutting speed",
"Sulu ve kuru delme opsiyonu": "Wet and dry drilling option",
"Elektrikli su pompası": "Electric water pump",

# PARAMS
"Maksimum Delme Çapı": "Max Drilling Diameter",
"Takım Tutucu": "Tool Holder",
"Maksimum Kesme Kalınlığı": "Max Cutting Thickness",
"Gövde Malzemesi": "Body Material",
"Maksimum Giriş Basıncı": "Max Inlet Pressure",
"İlerleme Tipi": "Feed Type",
"Su Tankı": "Water Tank",
"Devir Hızları": "Rotation Speeds",
"Gerekli Hidrolik Ünite": "Required Hydraulic Unit",
"Kullanım Gazları": "Applicable Gases",
"Su Tankı Kapasitesi": "Water Tank Capacity",
"Isıtma Sistemi": "Heating System",
"Çalışma Basıncı": "Working Pressure",
"Motor Gücü": "Motor Power",
"Maksimum Kesme Derinliği": "Max Cutting Depth",
"Motor": "Engine",
"Çıkış Basıncı": "Outlet Pressure",
"Çalışma Sıcaklığı": "Operating Temperature",
"Bağlantı Tipi": "Connection Type",
"Giriş Basıncı": "Inlet Pressure",
"Maksimum Kesme Uzunluğu": "Max Cutting Length",
"İlerleme Mesafesi": "Feed Distance",
"Sistem Sınıfı": "System Class",
"Kullanım Alanı": "Application Area",
"Temel Serim Genişliği": "Basic Paving Width",
"Regülatör Tipi": "Regulator Type",
"Sürüş Sistemi": "Drive System",
"Kafa Ağırlığı": "Head Weight",
"Çalışma Ağırlığı": "Operating Weight",
"ISO Sınıfı": "ISO Class",
"Kapak Malzemesi": "Cover Material",
"Delme Çapı Aralığı": "Drilling Diameter Range",
"Sürüş Tipi": "Drive Type",
"Minimum Hava İhtiyacı": "Min Air Requirement",
"Standart": "Standard",
"Çıkış Akış Aralığı": "Outlet Flow Range",
"Montaj Tipi": "Mounting Type",
"Hamlaç Boyu": "Torch Length",
"Su Pompası": "Water Pump",
"Germe Tipi": "Tensioning Type",
"Hazne Kapasitesi": "Hopper Capacity",
"Uyumlu Gazlar": "Compatible Gases",
"Motor Gücü / Kaynak": "Motor Power / Source",
"Motor Seçeneği": "Engine Option",
"Halat Depolama Kapasitesi": "Wire Storage Capacity",
"Sistem Ağırlığı": "System Weight",
"Ağırlık": "Weight",
"Darbe Sayısı": "Impact Rate",
"Darbe Gücü": "Impact Energy",

# VALUES
"Oksijen / Asetilen / Propan": "Oxygen / Acetylene / Propane",
"Elektrikli Isıtma": "Electric Heating",
"200 veya 300 bar": "200 or 300 bar",
"Dövme Pirinç": "Forged Brass",
"-20°C ile +60°C arası": "-20°C to +60°C",
"1500 - 2700 darbe/dk": "1500 - 2700 bpm",
"Elektrikli Dalgıç Pompa": "Electric Submersible Pump",
"Elektrik / Hidrolik": "Electric / Hydraulic",
"İç / Dış Mekan (Ağır Hizmet)": "Indoor / Outdoor (Heavy Duty)",
"Pnömatik": "Pneumatic",
"Hidrolik Kremayer": "Hydraulic Rack",
"Zn/Al Alaşım Basınçlı Döküm": "Zn/Al Alloy Die Cast",
"ISO 2503 Uyumlu": "ISO 2503 Compliant",
"Ağır Hizmet (Heavy Duty)": "Heavy Duty",
"Tek Kademeli Edge 2.0": "Single Stage Edge 2.0",
"Hidrostatik Otomatik İlerleme": "Hydrostatic Auto Feed",
"Römork / Kamyonet": "Trailer / Truck",
"35 Litre": "35 Liters",
"400 Litre": "400 Liters",
"Ar, Ar/CO2, CO2": "Ar, Ar/CO2, CO2",
"Oksijen, Argon, Karışım Gaz": "Oxygen, Argon, Mixed Gas",
"11 kW (Dizel)": "11 kW (Diesel)",
"Kubota Dizel": "Kubota Diesel",

# ACCESSORIES
"Duvar Kesme Diski Ø 1600 mm": "Wall Saw Blade Ø 1600 mm",
"Hidrolik Ünite": "Hydraulic Unit",
"Bağlantı Somunu": "Connection Nut",
"Hidrolik Hortum Seti": "Hydraulic Hose Set",
"Çıkış Rakoru": "Outlet Fitting",
"Tüp Bağlantı Rakoru": "Cylinder Connection Fitting",
"Uzatma Kolu": "Extension Arm",
"Buji Seti": "Spark Plug Set",
"Temizleme Çakısı": "Cleaning Tip",
"Elektrik Motoru": "Electric Motor",
"Uzatma Rayı 2m": "Extension Rail 2m",
"Karot Sehpası P-3000": "Core Stand P-3000",
"Gaz Hortumu": "Gas Hose",
"Adaptör Pulu": "Adapter Washer",
"Montaj Braketi": "Mounting Bracket",
"WP-12 Yedek Pompa": "WP-12 Spare Pump",
"Koruma Kapağı": "Protective Cover",
"Yetkili Servis Bakım Seti": "Authorized Service Maintenance Kit",
"Tabla Uzatma Aparatı": "Screed Extension Kit",
"Harici Su Pompası Uyumu": "External Water Pump Compatible",
"Karbon Fırça Seti": "Carbon Brush Set",
"Cedima Elmas Disk Ø 800 mm": "Cedima Diamond Blade Ø 800 mm",
"Test Karot Uçları": "Test Core Bits",
"Victor Kesme Lüleleri": "Victor Cutting Tips",
"Hava Kompresörü": "Air Compressor",
"Rezistans Çubukları": "Heating Elements",
"Şanzıman Yağı": "Gear Oil",
"Gaz Hortumları": "Gas Hoses",
"Tahrik Motoru": "Drive Motor",
"Mandren Adaptörü": "Chuck Adapter",
"Sulu Kesim Diski Ø 400 mm": "Wet Cutting Blade Ø 400 mm",
"Cedima Elmas Tel Halat": "Cedima Diamond Wire",
"Su Pompası": "Water Pump",
"Hava ve Yağ Filtreleri": "Air and Oil Filters",
"Konveyör Bantları": "Conveyor Belts",
"Özel Taşıma Çantası": "Special Carrying Case",
"Conta Seti": "Seal Kit",
"Debimetre Camı": "Flowmeter Glass",
"Bağlantı Rekorları": "Connection Fittings",
"SDS Max Keskiler": "SDS Max Chisels",
"Manometre Camı": "Pressure Gauge Glass",
"Yedek Parça Kodu: HYD-P5000": "Spare Part Code: HYD-P5000",
"Elmas Karot Uçları": "Diamond Core Bits",
}

data = json.load(open("src/data/products.json", "r", encoding="utf-8"))

for p in data:
    if "features" in p:
        p["featuresEn"] = [translation_dict.get(f, f) for f in p["features"]]
    if "technicalData" in p:
        p["technicalDataEn"] = []
        for t in p["technicalData"]:
            p["technicalDataEn"].append({
                "param": translation_dict.get(t["param"], t["param"]),
                "value": translation_dict.get(t["value"], t["value"]),
                "accessory": translation_dict.get(t["accessory"], t["accessory"])
            })

json.dump(data, open("src/data/products.json", "w", encoding="utf-8"), ensure_ascii=False, indent=2)

